---
title: "EpiLat Post: Inmunidad de rebaño"
subtitle: ""
author: "Zulma M. Cucunubá"
date: "12/11/2018"
output:
  rmarkdown::html_document:
    theme: spacelab
    highlight: zenburn
    code_folding: 
    toc: true
    toc_depth: 2
classoption: landscape
fontsize: 24pt


---

----------------------------------------------------------
Para volver a __EpiLat Blog__ https://zmcucunuba.github.io
----------------------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
# Introducción


La inmunidad de grupo o también llamada de rebaño es probablemente el concepto má importante en Epidemiología de las enfermedades infecciosas. Este concepto se refiere a la inmunidad que las personas vacunadas (natural o artificialmente) le confieren a las no vacunadas.

El concepto se hizo más popular cuando las vacunas fueron introducidad masivamante y hoy en día sabemos que este aplica al análisis de vacuans sino al análisis de cualqueir enfermedad infecciosa. 


# Teorema del límite de inmunidad (Immunity Threshold)

Este teorema desarrollado por Smit (1970) nos muestra que si la inmunidad protectora frente a una infección (por ejemplo al aplicar una vacuna) fuer aplicada de forma aleatoria en una población cuyo contacto es aleatorio, de tal manera que en promedio cada individuo entra en contacto con _R0_ individuos, la incidencia de la infección declinará cuando la proporción de individuos inmunes exceda en límite de inmunidad dado por $R_o - 1/ R_0$ o $1-1/R0$ (Hine P., 2011.)




# Referencias

Hine P et al. 2011. https://doi.org/10.1093/cid/cir007


